### ISSUE TITLE
Share button on homepage misleading

### ISSUE THREAD

**Issue by kamiranoff** [heron2014/flashcards#107]
The share button on the homepage looks like you want to share something. Instead, it is a screen to add a deck id. 
The UX is misleading

![Image from iOS (4)](https://user-images.githubusercontent.com/5861100/108593756-7ff00d00-736d-11eb-8302-48b9a81c910d.png)

**Comment by heron2014** [comment]
I added share icon because I wasnt sure which icon to use which is not a plus... Any idea which icon would make more sense which would not indicate create new deck.

**Comment by heron2014** [comment]
Changed to: ![Screenshot 2021-02-20 at 17 52 07](https://user-images.githubusercontent.com/8476884/108604215-72a24500-73a4-11eb-8a84-db56e4cb1c8d.png)
