### ISSUE TITLE
Couple of icons too close to the edge of the screen on IphoneX

### ISSUE THREAD

**Issue by kamiranoff** [heron2014/flashcards#108]
![Image from iOS (2)](https://user-images.githubusercontent.com/5861100/108593783-9f873580-736d-11eb-8a38-0bc9d75bc55b.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/5861100/108593786-a1e98f80-736d-11eb-85ed-82a8b9b65ebc.png)

**Comment by heron2014** [comment]
need to test on all devices :)
