### ISSUE TITLE
Share ID should only have alpha-numeric characters

### ISSUE THREAD

**Issue by kamiranoff** [heron2014/flashcards#109]
The share id contains `-` which is a character hard to find on the phone. To make it easier would be good to only use alpha numeric characters

![Image from iOS (3)](https://user-images.githubusercontent.com/5861100/108593807-d9f0d280-736d-11eb-9ada-2220043ead1d.png)

Also would be nice to make it bigger in a different style, for people to easily copy/paste it

**Comment by heron2014** [comment]
again good point :)

**Comment by heron2014** [comment]
I changed to 4 combination and made the text to be text input - hopefully that will be easier to copy.
