### ISSUE TITLE
Share deck feel like you actually gonna share a single question

### ISSUE THREAD

**Issue by kamiranoff** [heron2014/flashcards#110]
The share deck option only appears when you open a question.
The UX indicates that you are going to share one question. Not the entire deck

![Image from iOS](https://user-images.githubusercontent.com/5861100/108593838-20463180-736e-11eb-9238-e3dca6216531.png)

Maybe would be good to save questions individually if you want to browse/share the question and make your own deck from existing questions (v2/v3)

**Comment by heron2014** [comment]
ohh good points!! I need to re-think where to put the share button to be less questionable for the user!
