### ISSUE TITLE
editing deck title pushes deck to the last item on the list

### ISSUE THREAD

**Issue by heron2014** [heron2014/flashcards#173]
Bug:
Edit deck title and see where the deck is placed.

Desire behaviour:
Deck should not change position by editing title.

**Comment by kamiranoff** [comment]
I am not reproducing.

**Comment by kamiranoff** [comment]
Is it a shared deck? Can you give more details about the bug?

**Comment by kamiranoff** [comment]
Is it ios or android? Made a fix for a keyboard issue on android but not sure if related.

**Comment by heron2014** [comment]
its on real device - on simulator the bug doesn't appear. 

Reproduce steps: 
create 5 decks in real device, click on pen to edit and after editing click enter on your device keyboard, the deck is moved to the end - at least on my phone.
